# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'  Find column with same non-positive values
#'
find_same_col <- function(invmatrix) {
    .Call(`_contrastable_find_same_col`, invmatrix)
}

